export interface Filter {
  field: string
  value: string
}

export interface FilterOption {
  label: string
  value: string
  path: string
}


export const baseFilterOptions: FilterOption[] = [
  { label: "User Name", value: "userName", path: "jsonPayload.event.userName" },
  { label: "User Email", value: "userEmail", path: "jsonPayload.event.userEmail" },
  { label: "User Action", value: "userAction", path: "jsonPayload.event.userAction" },
  { label: "User Id", value: "userId", path: "jsonPayload.event.userId" },
  { label: "Message", value: "message", path: "jsonPayload.event.message" },
  { label: "Source Application", value: "sourceApplication", path: "jsonPayload.event.sourceApplication" },
  { label: "HTTP Method", value: "httpMethod", path: "jsonPayload.event.httpMethod" },
]

export const podList = [
  "auditdataprovider-web",
  "adplatintegration-prod-can-web",
  "adplatintegration-prod-usa-web",
  "advertiserservice-prod-can-web",
  "advertiserservice-prod-usa-web",
  "billingservice-prod-can-web",
  "billingservice-prod-usa-web",
  "businessservice-prod-can-web",
  "businessservice-prod-usa-web",
  "businessuserservice-prod-can-web",
  "businessuserservice-prod-usa-web",
  "callcapconnector-prod-usa-web",
  "campaignperformance-prod-can-web",
  "campaignperformance-prod-usa-web",
  "campaignservicev2-prod-can-web",
  "campaignservicev2-prod-usa-web",
  "campaignservicev3-prod-can-web",
  "campaignservicev3-prod-usa-web",
  "clientviewapi-prod-can-web",
  "clientviewapi-prod-usa-web",
  "cts-prod-can-web",
  "cts-prod-usa-web",
  "ctsadminapi-prod-can-web",
  "ctsadmingatewayv2-prod-can-web",
  "ctsadmingatewayv2-prod-usa-web",
  "ctsadminui-prod-can-web",
  "ctsadminui-prod-usa-web",
  "directdebitbatchvaultusa-prod-usa-web",
  "directdebitservicebatch-prod-usa-web",
  "dmszeroapi-prod-usa-web",
  "dmszeroui-prod-usa-web",
  "eds-prod-can-web",
  "eds-prod-usa-web",
  "eventapi-prod-can-web",
  "eventapi-prod-usa-web",
  "eventreporter-prod-can-web",
  "eventreporter-prod-usa-web",
  "googlegeocodeconnector-prod-usa-web",
  "ldapapis-prod-usa-web",
  "ldapservice-prod-usa-web",
  "marchexconnector-prod-can-web",
  "marchexconnector-prod-usa-web",
  "mediaapis-prod-can-web",
  "mediaapis-prod-usa-web",
  "mediaautomation-prod-can-web",
  "mediaautomation-prod-usa-web",
  "n8npipelines-prod-usa-web",
  "notif-prod-usa-web",
  "offerservice-prod-can-web",
  "offerservice-prod-usa-web",
  "orderintegrationservice-prod-usa-web",
  "paymentgateway-prod-usa-web",
  "paymentservice-prod-can-web",
  "paymentservice-prod-usa-web",
  "paymentservicev2-prod-can-web",
  "paymentservicev2-prod-usa-web",
  "paymentvault-prod-can-web",
  "paymentvault-prod-usa-web",
  "platformadminservices-prod-usa-web",
  "platformadminui-prod-usa-web",
  "platformservice-prod-can-web",
  "platformservice-prod-usa-web",
  "platwebdocker-prod-can-web",
  "productsubscriptionapi-prod-can-web",
  "productsubscriptionapi-prod-usa-web",
  "pubservices-prod-can-web",
  "pubservices-prod-usa-web",
  "qtcclient-prod-can-web",
  "qtcclient-prod-usa-web",
  "qtcgateway-prod-usa-web",
  "qtcglobalservice-prod-usa-web",
  "reachpay-prod-usa-web",
  "rliapi-prod-can-web",
  "selfserveadgateway-prod-usa-web",
  "serviceassignment-prod-can-web",
  "serviceassignment-prod-usa-web",
  "sf2dbbatch-prod-usa-web",
  "sitegenerationapi-prod-usa-web",
  "siteimpactreports-prod-usa-web",
  "stripesaasgateway-prod-usa-web",
  "tableaubatch-prod-usa-web",
  "telmetricsconnector-prod-can-web",
  "telmetricsconnector-prod-usa-web",
  "twilioconnector-prod-can-web",
  "twilioconnector-prod-usa-web",
  "validationcontroller-prod-usa-web",
  "xbas-prod-can-web",
  "xbas-prod-usa-web",
  "admincenterdashboard-prod-can-web",
  "admincenterdashboard-prod-usa-web",
  "madminclient-prod-can-web",
  "madminclient-prod-usa-web",
  "madmindashboardetl-prod-can-web",
  "madmindashboardetl-prod-usa-web",
  "mediachangehistoryapi-prod-can-web",
  "mediachangehistoryapi-prod-usa-web",
  "mediacoregateway-prod-can-web",
  "mediacoregateway-prod-usa-web",
  "mediacoreui-prod-can-web",
  "mediacoreui-prod-usa-web",
  "mediareporting-prod-can-web",
  "mediareporting-prod-usa-web",
  "captureadmin-prod-usa-web",
  "captureapi-prod-usa-web",
  "capturecompatible-prod-usa-web",
  "captureexternaleventapi-prod-usa-web",
  "captureinstallstatusapi-prod-usa-web",
  "capturejsconfigapi-prod-usa-web",
  "capturelogger-prod-usa-web",
  "captureondemand-prod-usa-web",
  "configcombinator-prod-usa-web",
  "dmsentryhandler-prod-can-web",
  "dmsentryhandler-prod-usa-web",
  "dmsentryhandlerrtsys-prod-can-web",
  "dmsentryhandlerrtsys-prod-usa-web",
  "localiqfirstpartydata-prod-usa-web",
  "lsareceiver-prod-usa-web",
  "siteservice-prod-usa-web",
  "edgefamilyprovisioningagent-prod-can-web",
  "edgefamilyprovisioningagent-prod-usa-web",
  "elastisyncelixir-prod-usa-web",
  "graphqlapi-prod-usa-web",
  "nextui-prod-usa-web",
  "reachconvert-prod-usa-web",
  "reachconvertui-prod-usa-web",
  "reachconvertui-prod-usa-wl-web",
  "rollupreporting-prod-usa-web",
  "activityservice-prod-usa-web",
  "argonapi-prod-usa-web",
  "argoncalendar-prod-usa-web",
  "argongateway-prod-usa-web",
  "argonstream-prod-usa-web",
  "buyonlinedirectui-prod-usa-web",
  "carbonapi-prod-usa-web",
  "cobaltui-prod-usa-web",
  "dmsaiembeddings-prod-usa-web",
  "dmsinteractionservice-prod-usa-web",
  "freemiumleadsservice-prod-usa-web",
  "localiqdmsaccountservicesapi-prod-usa-web",
  "localiqdmsaccountservicesui-prod-usa-web",
  "neonapi-prod-usa-web",
  "premiumlistingsservice-prod-usa-web",
  "productsettingsui-prod-usa-web",
  "reachsitessalestool-prod-usa-web",
  "datascienceleadestimation-prod-usa-web",
  "localiqgraderanalyticsbudgetestimates-prod-can-web",
  "localiqgraderanalyticsbudgetestimates-prod-usa-web",
  "localiqgraderanalyticsgannettdisplay-prod-usa-web",
  "localiqgraderanalyticsreachdisplay-prod-can-web",
  "localiqgraderanalyticsreachdisplay-prod-usa-web",
  "localiqgraderanalyticssearch-prod-can-web",
  "localiqgraderanalyticssearch-prod-usa-web",
  "localiqgraderanalyticssilktidesummary-prod-can-web",
  "localiqgraderanalyticssilktidesummary-prod-usa-web",
  "localiqgraderanalyticssocial-prod-can-web",
  "localiqgraderanalyticssocial-prod-usa-web",
  "localiqgraderanalyticsyoutube-prod-can-web",
  "localiqgraderanalyticsyoutube-prod-usa-web",
  "startingbids-prod-can-web",
  "startingbids-prod-usa-web",
  "xmediadsapi-prod-usa-web",
  "leadsaiservices-prod-can-web",
  "leadsaiservices-prod-usa-web"
]
